# Generated by Django 3.1.1 on 2020-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201112_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Russian', 'Russian'), ('English', 'O vy iz Ameriki?'), ('Kazakh', 'Aktau the best')], default='Russian', max_length=1222, verbose_name='Language'),
        ),
    ]
