# Generated by Django 3.1.1 on 2020-11-12 16:56

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Russian', 'Russian'), ('English', 'O vy iz Ameriki?'), ('Kazakh', 'Aktau the best')], default='Russian', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Russian', 'Russian'), ('English', 'O vy iz Ameriki?'), ('Kazakh', 'Aktau the best')], default='Russian', max_length=1222, verbose_name=catalog.models.Language),
        ),
    ]
