# Generated by Django 3.1.1 on 2020-11-12 17:21

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201112_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Russian', help_text='Select a language for this book', max_length=122112, verbose_name=catalog.models.Language),
        ),
    ]
